### ISSUE TITLE
How can we update the position of Annotations?

### ISSUE THREAD

**Issue by sandorbogyo** [pauljohanneskraft/Map#15]
In my app a timer updates the positions every 15 seconds, but I don't want the old Annotation to be deleted and a new one created. The goal would be to update the annotation position with animation. Is this possible?

**Comment by pauljohanneskraft** [comment]
I think with the current Map implementation here (or the SwiftUI version in MapKit itself), this is not possible. What I am wondering though, is, if that is possible with MKAnnotation on a MKMapView - do you have any insight into this?

**Comment by sandorbogyo** [comment]
I used to use this implementation, maybe we can start with this.  I checked the id to see if this annotation was already in the existing annotations, if so, just change its position.

```
let currentAnnotations = mapView.mapViewAnnotations //On the map
        let updatedAnnotations = currentAnnotations.filter { mapAnnotation in
            self.annotations.contains { $0.id == mapAnnotation.id && $0.coordinate != mapAnnotation.coordinate  }
            //Previous annotations = self.annotations
        }
        
        for updatedAnnotation in updatedAnnotations {
            let currentNewAnnotation = self.annotations.first { $0.id == updatedAnnotation.id}!
            UIView.animate(withDuration: 0.25) {
                updatedAnnotation.coordinate = currentNewAnnotation.coordinate
            }
        }
```

**Comment by pauljohanneskraft** [comment]
I have tried it and it works exactly as expected - so feel free to use the implementation above - possibly with a `UIView.animate` around the setting of the coordinate inside the `sink`, i.e.

```swift
@objc
class UpdatingMapAnnotation: NSObject, MKAnnotation {

    dynamic var coordinate: CLLocationCoordinate2D

    private var coordinateCancellable: Cancellable?

    init<P: Publisher>(coordinate: CLLocationCoordinate2D, publisher: P) where P.Output == CLLocationCoordinate2D, P.Failure == Never {
        self.coordinate = coordinate

        super.init()

        coordinateCancellable = publisher
            .sink { [weak self] newValue in
                // I changed unowned to weak, since we are now in another async context
                // and the instance could (although highly unlikely) be gone until the animation is performed
                UIView.animate(withDuration: 0.25) {
                    self?.coordinate = newValue
                }
            }
    }

}
```

Closing this for now - if you have follow-up questions or this does not solve the issue, let me know and I will reopen.
