### ISSUE TITLE
ViewMapAnnotation does not allow text

### ISSUE THREAD

**Issue by ale-ben** [pauljohanneskraft/Map#21]
I'm trying to make an annotation with text and icon (like the official POI's in apple maps) but the text is not displayed.

This is the code I'm using, with SwiftUI maps it works but with this library it doesn't.
``` 
Map(
  coordinateRegion: $region,
  pointOfInterestFilter: .excludingAll,
  annotationItems: POIList){ item in
    ViewMapAnnotation(coordinate: item.coordinate) {
        VStack{
            Text("Text Here")
            Image(systemName: "leaf.circle.fill")
            
        }
        //MapPOIElementView(POI: item)
    }
  }
```

Expected result (MapKit):
<img width="211" alt="Screenshot 2022-07-30 at 16 47 41" src="https://user-images.githubusercontent.com/17771264/181919614-4898bf84-1341-4dc4-9fe6-a424eee738d8.png">

Actual result (Map):
<img width="119" alt="Screenshot 2022-07-30 at 16 44 05" src="https://user-images.githubusercontent.com/17771264/181919484-357ab2d3-fd00-4218-93e0-b6e31637621c.png">

**Comment by pauljohanneskraft** [comment]
Hey @ale-ben ! I have just tried this out and can confirm that this is an issue at the moment - I tried putting `.fixedSize()` on the view and it seems to have fixed the issue - can you confirm that this is the case?

This is only required as a temporary workaround though, as I will make sure that this is handled by the framework itself - thank you for letting me/us know!

**Comment by ale-ben** [comment]
Sorry for the late reply, can confirm that with .fixedSize() labels are shown.
