### ISSUE TITLE
Package not recognised

### ISSUE THREAD

**Issue by ahartman** [pauljohanneskraft/Map#29]
Dear Paul,

I added your package 'Map' to my project as explained by Apple.
My project has a working map based on MapKit but I want to use extended facilities based on your package.
It is visible as a Package dependency as well as listed under'Frameworks, Libraries and embedded Content'.

However it seems not to be recognised by Xcode as I get 'Cannot find type 'MKCoordinateRegion' in scope and similar errors for MyLocation, MKDirections and UserTrackingMode.

Any ideas how to resolve this.
Kind regards, ahartman, belgium

**Comment by pauljohanneskraft** [comment]
MKCoordinateRegion is not defined in this package but rather in MapKit - so you will need to put `import MapKit` at the top of the file to use MapKit-defined APIs. We might want to change this in the future though, since it would make sense to simply re-export the MapKit interface as well.

**Comment by ahartman** [comment]
Thank you for the quick reply. It would be good to update the example code given in REEDME as this does not show importing Mapkit. 
Kind regards, ahartman, belgium

**Comment by ahartman** [comment]
Dear Paul,
I am struggling with two things and I am not very good in reading code to find how to use it:
1. I want to draw 3 concentric circles with different radiuses and colours from the center of the map but I cannot adapt the overlay example code to work. Can you help a bit here?
2. I  also wanted to use MapZoomControl to enable zooming on my Mac; then I realised a ZoomControl is only available on a native Mac app and your code does not work in that fashion. It works fine for Mac Catalyst but the app then behaves like an iPad, i.e., no zoom control. Do you have any idea how to zoom a map on a iMac with keyboard and mouse but no touch pad?

Kind regards, ahartman, belgium

**Comment by pauljohanneskraft** [comment]
Hey, sorry for responding so late.

1. If they should only be on top of the map regardless of coordinates, please simply use SwiftUI's overlay functionality.

For coordinate-fixed circles, you may want to use the following example:

```swift
struct MapOverlayCircle: Identifiable {
    let id = UUID()
    let center: CLLocationCoordinate2D
    let radius: CLLocationDistance
    let strokeColor: Color
}

struct MyMapView: View {

    @State private var overlays = [
        MapOverlayCircle(...),
        MapOverlayCircle(...),
    ]

    @State private var region = MKCoordinateRegion()    

    var body: some View {
        Map(
            coordinateRegion: $region,
            overlayItems: overlays
         ) { overlay in
               MapCircle(center: overlay.center, radius: overlay.radius, strokeColor: overlay.strokeColor)
         }
    }
}
```

This example will draw two circles on the map (the initializers would need to be filled instead of the ellipsis (...) of course). 
For more customization, you might want to have a deeper look into MapCircle initializers.

2. MapZoomControl is only available on Mac - maybe you try to build the app for an iOS target and then it fails?

For these cases, please make sure that MapZoomControl is only referenced in macOS code, for example using the following precompiler directives:

```swift
Map(
    coordinateRegion: $region,
    annotationItems: mainModel.mapElementLines
) { mapLocation in
   MapPin(coordinate: mapLocation.coordinate!, tint: mapLocation.color)}
)
.mapKey(1)
if os(macOS)
.overlay(alignment: .topLeading) {
    MapZoomControl(key: 1)
}
#endif
```

**Comment by ahartman** [comment]
Paul,
Better a late answer than no answer, thank you.
How do I combine annotationItems and the circles on a single map?

`
struct PatientsPinsCirclesView: View {
    static var home = CLLocationCoordinate2D(latitude: 51.35988, longitude: 4.48369)
    @EnvironmentObject var model: MainModel
    @State private var region = MKCoordinateRegion(
        center: home,
        span: MKCoordinateSpan(latitudeDelta: 0.6, longitudeDelta: 0.6)
    )
    @State private var overlays = [
        MapOverlayCircle(center: home, radius: 5000.0, strokeColor: .blue),
        MapOverlayCircle(center: home, radius: 10000.0, strokeColor: .green),
        MapOverlayCircle(center: home, radius: 15000.0, strokeColor: .red),
        MapOverlayCircle(center: home, radius: 30000.0, strokeColor: .black),
    ]

    var body: some View {
        VStack {
            Map(coordinateRegion: $region,
                annotationItems: model.mapPins) {
                mapPin in
                MapPin(coordinate: mapPin.coordinate, tint: mapPin.color)
            }
        }
    }
}
`

Concerning the zoom control, my app is for Mac and iPad, so I can do that with if os(macOs).

Regards, ahartman, belgium

**Comment by ahartman** [comment]
Paul,

Better a later answer than no answer, thank you for getting back to me.
I got your overlay example to work. However, I have no idea how to combine annotations AND circles on one map.
The code below of course displays two maps and I want to pins and the circles the same map.

The MapZoomControl is not visible with your code.

`import SwiftUI
import MapKit
import Map

struct PatientsPinsView: View {
    @EnvironmentObject var model: MainModel
    @State private var region = MKCoordinateRegion(
        center: CLLocationCoordinate2D(latitude: 51.35988, longitude: 4.48369),
        span: MKCoordinateSpan(latitudeDelta: 0.6, longitudeDelta: 0.6)
    )
    
    var body: some View {
        VStack {
            Map(coordinateRegion: $region,
                annotationItems: model.mapPins) {
                mapPin in
                MapPin(coordinate: mapPin.coordinate, tint: mapPin.color)
            }
                .mapKey(1)
#if os(macOS)
                .overlay(alignment: .topLeading) {
                    MapZoomControl(key: 1)
                }
#endif
        }
    }
}`

**Comment by pauljohanneskraft** [comment]
You can provide overlays and annotations in the same initializer of a map

```swift
var body: some View {
    Map(
        coordinateRegion: $region,
        annotationItems: model.mapPins,
        annotationContent: { mapPin in
            MapPin(coordinate: mapPin.coordinate, tint: mapPin.color)
        },
        overlayItems: overlays,
        overlayContent: { overlay in
            MapCircle(center: overlay.center, radius: overlay.radius, strokeColor: UIColor(overlay.strokeColor))
        }
    )
    .mapKey(1)
    #if os(macOS)
    .overlay(alignment: .topLeading) {
        MapZoomControl(key: 1)
    }
    #endif
}
```

Does that work for you? 😊

**Comment by ahartman** [comment]
Paul,

Yes, that works. I tried the same thing but got weird errors. By comparing yours with mine, I found one single stupid typo!

As for the MapZoomControl, I develop for Mac Catalyst, and I presume Catalyst does not qualify as MacOS. That is a pity but I can zoom with double-click and alt-double-click.

Thanks for now and I follow you for updates in your package, good work.

Regards, André Hartman

**Comment by pauljohanneskraft** [comment]
There is unfortunately no such functionality from MapKit, you can however show the current zoom status by setting the `informationVisbility` to include `MapInformationVisbility.scale` - you can do this for example like this:

```swift
var body: some View {
    Map(
        coordinateRegion: $region,
        informationVisbility: .default.union(.scale), // You can also try other values such as `.all` to show all kinds of information
        annotationItems: model.mapPins,
        annotationContent: { mapPin in
            MapPin(coordinate: mapPin.coordinate, tint: mapPin.color)
        },
        overlayItems: overlays,
        overlayContent: { overlay in
            MapCircle(center: overlay.center, radius: overlay.radius, strokeColor: UIColor(overlay.strokeColor))
        }
    )
    .mapKey(1)
    #if os(macOS)
    .overlay(alignment: .topLeading) {
        MapZoomControl(key: 1)
    }
    #endif
}
```

**Comment by pauljohanneskraft** [comment]
#32 should make MapZoomControl and MapPitchControl available for macCatalyst - have you found anything else that doesn't seem to be available for macCatalyst but actually should be?

**Comment by pauljohanneskraft** [comment]
Yes, annotation clustering should be available, I agree, I just haven't found the time nor resources to implement it yet. If you happen to have an idea or suggestion, feel free to open another issue or pull request 😊

**Comment by pauljohanneskraft** [comment]
> According to Apple documentation, there is something like Annotation Declustering, but it very dense for me. Look at: [https://developer.apple.com/documentation/mapkit/mkannotationview/decluttering_a_map_with_mapkit_annotation_clustering](url)

Thank you for that link - unfortunately, I cannot implement this right now, but I will try to find some time in the coming weeks.

**Comment by pauljohanneskraft** [comment]
> According to Apple documentation, there is something like Annotation Declustering, but it very dense for me. Look at: [https://developer.apple.com/documentation/mapkit/mkannotationview/decluttering_a_map_with_mapkit_annotation_clustering](url)

Thank you for that link - unfortunately, I cannot implement this right now, but I will try to find some time in the coming weeks.

**Comment by ahartman** [comment]
Paul,

Please find my code below as as a screen image of the result.
My wife has a psychology practice and the map shows where patients come from in distance for the practice.

```
import Map
import MapKit
import SwiftUI

struct PatientsPinsView: View {
    @EnvironmentObject var model: MainModel
    var body: some View {
        ZStack {
            doMapView()
            doLegend()
        }
        .navigationBarTitleDisplayMode(.inline)
        .statusBar(hidden: true)
    }
}

struct doMapView: View {
    @EnvironmentObject var model: MainModel
    static var home = CLLocationCoordinate2D(latitude: 51.35988, longitude: 4.48369)
    @State var region = MKCoordinateRegion(
        center: home,
        latitudinalMeters: 40000.0, longitudinalMeters: 40000.0
    )

    var body: some View {
        VStack {
            Map(
                coordinateRegion: $region,
                annotationItems: model.mapPins,
                annotationContent: { element in
                    MapPin(coordinate: element.coordinate, tint: element.color)
                },
                overlayItems: getCircles(),
                overlayContent: { element in
                    MapCircle(
                        center: element.center,
                        radius: element.radius,
                        lineWidth: 3,
                        strokeColor: UIColor(element.strokeColor)
                    )
                }
            )
        }
    }

    func getCircles() -> [MapOverlayCircle] {
        return [
            MapOverlayCircle(center: doMapView.home, radius: 5000.0, strokeColor: .blue),
            MapOverlayCircle(center: doMapView.home, radius: 10000.0, strokeColor: .green),
            MapOverlayCircle(center: doMapView.home, radius: 15000.0, strokeColor: .red)
        ]
    }
}

struct doLegend: View {
    @EnvironmentObject var model: MainModel
    let columns = [GridItem(.fixed(80)), GridItem(.fixed(80)), GridItem(.fixed(80))]
    var body: some View {
        VStack {
            HStack {
                Spacer()
                LazyVGrid(columns: columns) {
                    Text("Afstand")
                        .underline()
                    Text("Aantal")
                        .underline()
                    Text("Procent")
                        .underline()
                    ForEach(model.mapLegend, id: \.self) { legend in
                        Text(legend.distance)
                        Text(legend.count)
                        Text(legend.percentage)
                    }
                }
                .border(.black)
                .background(Color.white.opacity(0.7))
                .padding([.trailing], 50)
                .padding([.top], 20)
                .frame(maxWidth: 240)
            }
            Spacer()
        }
    }
}

struct MapOverlayCircle: Identifiable {
    let id = UUID()
    let center: CLLocationCoordinate2D
    let radius: CLLocationDistance
    let strokeColor: Color
}

struct PatientsPinsView_Previews: PreviewProvider {
    static var previews: some View {
        PatientsPinsView()
    }
}
```
<img width="1855" alt="Schermafbeelding 2023-02-10 om 11 56 53" src="https://user-images.githubusercontent.com/688316/218075821-03e7cb44-5be0-4097-8a63-7f293716125e.png">

**Comment by pauljohanneskraft** [comment]
Sure, okay, I have a couple (small) remarks:

1. Please make sure to have the circles wrapped in `@State` - otherwise the overlays will be regenerated all the times, since the uuids will change.

2. There is no such functionality to call this show-method - but you could write a method to center the map accordingly.

Let me give you a helper method that might be of help:

```swift
extension MKCoordinateRegion {
    convenience init(containing coordinates: [CLLocationCoordinate2D], multiplyingSpanBy spanFactor: Double = 1) {
        guard let minLatitude = coordinates.map(\.latitude).min(),
                   let maxLatitude = coordinates.map(\.latitude).max(),
                   let minLongitude = coordinates.map(\.longitude).min(),
                   let maxLongitude = coordinates.map(\.longitude).max() else {
            self.init()
            return
        }
        let latitudeDelta = (maxLatitude - minLatitude) * spanFactor // The spanFactor allows you to show a bit more than only the coordinates, e.g. put in `1.5` to see a bit more map than you would actually need to fit the coordinates
        let longitudeDelta = (maxLongitude - minLongitude) * spanFactor
        self.init(
            center: CLLocationCoordinate2D(
                latitude: minLatitude + (latitudeDelta / 2),
                longitude: minLongitude + (longitudeDelta / 2)
            ),
            span: MKCoordinateSpan(
                latitudeDelta: latitudeDelta,
                longitudeDelta: longitudeDelta
            )
        )
    }
}
```

Warning: This will only work, if the coordinates are not close to the Pacific (which I assume is the case here). An issue would arise, if you had one coordinate in California and one in Japan for example, since the average of their longitudes would be somewhere in Europe, which makes no sense. You would need to use trigonometric functions then to compute the average, which I skipped here.

You can then set your region in an `onAppear` / `task` modifier, like this:

```swift
@State private var region = MKCoordinateRegion()

var body: some View {
    Map(...)
        .task { region = MKCoordinateRegion(containing: model.mapPins.map(\.coordinate), multiplyingSpanBy: 1.5) }
}
```

**Comment by ahartman** [comment]
Paul,

Thank you for the helper, that works; however, the map gets drawn differently than I would expect.
The first image below is with spanFactor = 1. You can observe a black pin bottom-left and on the right hand edge, so the map is ok.
The second image is with a spanFactor of 1.5. It looks as if the map adds room only on the right hand side. The pin near Arendonk is well away from the map edge; however, the bottom-left one is still right on the edge.


<img width="1855" alt="Schermafbeelding 2023-02-11 om 09 36 12" src="https://user-images.githubusercontent.com/688316/218249144-906ca387-e258-4ebf-9f08-295a4da99efe.png">

<img width="1855" alt="Schermafbeelding 2023-02-11 om 09 37 09" src="https://user-images.githubusercontent.com/688316/218249158-8feeb09e-e32f-4365-a4a0-aad68338f49d.png">

**Comment by ahartman** [comment]
Paul, 

Thank you for the Helper, that works.
However, I see weird things in how the map gets redrawn when you change the spanFactor.
I also see differences in the maps as drawn by your package and by an earlier View that I made with plain MapKit and UIViewRepresentable. I will compose a message with images later.

Regards, André Hartman

**Comment by ahartman** [comment]
Paul, 

Please find my code. below:
Map window:
```
import Map
import MapKit
import SwiftUI

struct PatientsPinsView: View {
    var body: some View {
        ZStack {
            doMapView()
            doLegend()
        }
        .navigationBarTitleDisplayMode(.inline)
        .statusBar(hidden: true)
    }
}

struct doMapView: View {
    @EnvironmentObject var model: MainModel
    let home = CLLocationCoordinate2D(latitude: 51.35988, longitude: 4.48369)

    var body: some View {
        VStack {
            Map(
                coordinateRegion: $model.mapRegion,
                annotationItems: model.mapPins,
                annotationContent: { element in
                    MapPin(coordinate: element.coordinate, tint: element.color)
                },
                overlayItems: getCircles(),
                overlayContent: { element in
                    MapCircle(
                        center: element.center,
                        radius: element.radius,
                        lineWidth: 3,
                        strokeColor: UIColor(element.strokeColor)
                    )
                }
            )
        }
    }

    func getCircles() -> [MapOverlayCircle] {
        return [
            MapOverlayCircle(center: model.home, radius: 5000.0, strokeColor: .blue),
            MapOverlayCircle(center: model.home, radius: 10000.0, strokeColor: .green),
            MapOverlayCircle(center: model.home, radius: 15000.0, strokeColor: .red)
        ]
    }
}

struct doLegend: View {
    @EnvironmentObject var model: MainModel
    let columns = [GridItem(.fixed(80)), GridItem(.fixed(80)), GridItem(.fixed(80))]
    var body: some View {
        VStack {
            HStack {
                Spacer()
                LazyVGrid(columns: columns) {
                    Text("Afstand")
                        .underline()
                    Text("Aantal")
                        .underline()
                    Text("Procent")
                        .underline()
                    ForEach(model.mapLegend, id: \.self) { legend in
                        Text(legend.distance)
                        Text(legend.count)
                        Text(legend.percentage)
                    }
                }
                .border(.black)
                .background(Color.white.opacity(0.7))
                .padding([.trailing], 50)
                .padding([.top], 20)
                .frame(maxWidth: 240)
            }
            Spacer()
        }
    }
}

struct MapOverlayCircle: Identifiable {
    let id = UUID()
    let center: CLLocationCoordinate2D
    let radius: CLLocationDistance
    let strokeColor: Color
}

struct PatientsPinsView_Previews: PreviewProvider {
    static var previews: some View {
        PatientsPinsView()
    }
}
```

**Comment by pauljohanneskraft** [comment]
Since your original question and hopefully all further questions are solved, I will close this thread. If you happen to have follow-up questions, feel free to reopen / add comments and for unrelated questions feel free to open new issues.
