### ISSUE TITLE
impossible to have my liste of annotations

### ISSUE THREAD

**Issue by Flyer74** [pauljohanneskraft/Map#30]
Hello ! 

Thanks for the great work in this project ! 
I just Have a small issues when using map annotations. 

I've got a structured array : 

```
var places: [PointOfInterest] = []

struct PointOfInterest: Identifiable {

    let id = UUID()
    let name: String
    let latitude: Double
    let longitude: Double
    
    var coordinate: CLLocationCoordinate2D {
        CLLocationCoordinate2D(latitude: latitude, longitude: longitude)
    }
}
```

And I use it like this in my Map : 

```
Map(coordinateRegion: $region, type: getTypeFromUD(), annotationItems: places, annotationContent: { item in

                MapMarker(coordinate: item.coordinate, tint: UIColor(.red))   
  
})
```

My array receive data during the user use the app. When I go to my view where is my map I see only 1 pin which isn't at a corresponding place in my array. But can't see the other ?

I don't know how to deal with that ?

**Comment by pauljohanneskraft** [comment]
Hello @Flyer74 !

Is the `places` property wrapped in `@State` or `@Published` inside an `ObservableObject` conforming class that is then used with `@ObservedObject`, `@StateObject` or `@EnvironmentObject`?

Assuming from the code example above, places is a global property and as such will not notify your app/view about it changing and therefore, the map has no possibility to know that there are new places available.

Please make sure to correctly observe changes to the `places` variable and then it should work as expected.

I will close this for now - if the issue remains, please let me know by adding another comment, reopening the issue or opening another issue (if there is a follow-up issue that is not concerning the same topic).
